version: "3.7"

services:
  backend:
    build:
      context: ./backend
    image: backend:1.0.0
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    env_file:
      - ./.env

  me:
    build:
      context: ./me
    image: me:1.0.0
    container_name: me
    ports:
      - 8060:80